language: node_js

sudo: false

cache: npm

# test on node.js versions
node_js:
  - '16'
  - '14'

services:
  - redis-server

install:
  # ensure unexpected changes to yarn.lock break the build
  - npm install

script:
  - npm run test

after_script:
  - npm run coveralls
